apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream backend {
        server user-service:5001;
        server salle-service:5002;
        server reservation-service:5003;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
